# Generated by Django 4.2.3 on 2023-08-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('period', models.CharField(choices=[(None, 'Выбрать'), ('Ежедневно', 'Ежедневно'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Ежедневно', max_length=50, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[(None, 'Выбрать'), ('создана', 'создана'), ('запущена', 'запущена'), ('завершена', 'завершена')], default='создана', max_length=50, verbose_name='Статус')),
                ('time', models.TimeField(verbose_name='Время')),
                ('client', models.ManyToManyField(to='clients.client', verbose_name='Клиент рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='SenderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ошибка', 'Ошибка'), ('Отправлено', 'Отправлено')], default='Отправлено', max_length=50, verbose_name='Статус')),
                ('last_try', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата последней попытки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.sender', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
            },
        ),
    ]
