# Generated by Django 4.2.3 on 2023-08-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_alter_sender_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sender',
            options={'ordering': ('subject',), 'permissions': [('set_disabled', 'Can disable Рассылка')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
