# Generated by Django 4.2.3 on 2023-08-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Электронный адрес'),
        ),
    ]
